### ISSUE TITLE
architext UI options

### ISSUE THREAD

**Issue by molleweide** [vigoux/architext.nvim#4]
Hi again Vigoux,

Idea:

When you call `ArchitextREPL` you coul optionally edit the query in a buffer split or a `nui.nvim` popup so that one can more freely move around and edit the query and also save the query to a templates dir. (edit: I just saw that you have also made a template plugin which I am going to checkout)

I will look into this because it could be quite fun.

Cheers,

**Comment by molleweide** [comment]
I close this because I missunderstood how it worked initially and it does exactly what I am describing above lol..

**Comment by vigoux** [comment]
Hey, I don't think that this is the case for now though, and maybe we can have some further options for this architext REPL.
Honestly, the REPL is a fairly unused feature from me, it was just the beginning of the plugin, and now I recommend using the `:A` or `:Architext` commands rather than something else.
